- name: Start Docker Container
  docker_container:
    name: "centos-{{ item }}"
    state: "{{ state }}"
    image: sbeliakou/ansible-training:centos
    privileged: true
  with_sequence: count= "{{ count }}""
  register: centos


- name: Compose In-Memory Inventory
  add_host:
    name: "{{ container.NetworkSettings.IPAddress }}"
    ansible_host: "{{ container.Name }}"
    ansible_connection: docker
    groups:
      - loadbalancer
  loop: "[{{ centos.results[0] }}]"
  loop_control:
    label: "{{ container.Name }}"
  vars:
    container: "{{ item.ansible_facts.docker_container }}"

- name: Compose In-Memory Inventory
  add_host:
    name: "{{ container.NetworkSettings.IPAddress }}"
    ansible_host: "{{ container.Name }}"
    ansible_connection: docker
    groups:
      - backends
  loop: "{{ centos.results[1:] }}"
  loop_control:
    label: "{{ container.Name }}"
  vars:
    container: "{{ item.ansible_facts.docker_container }}"

- debug: var=groups

- name: Destroy
  gather_facts: no
  docker_container: 
    name: "{{ hostvars[item].ansible_host }}"
    state: "{{ state }}"
  loop: "{{ groups['backends'] + groups['loadbalancer'] }}"
  tags:
    - never
    - destroy