- hosts: appservers
  vars:
    - usr: vagrant
  tasks:
    - name: uid
      getent:
        database: passwd
        split: ' '
      register: passwd_data 

    - debug: 
        msg: >-
          {{ passwd_data.ansible_facts.getent_passwd | dict2items | map(attribute='key') | join(':') | split(':') | select('match', 'root') }}
      # with_dict:
      #   - "{{ passwd_data }}"