- name: systemd daemon reload
  systemd: 
    daemon_reload: yes
  become: yes

- name: restart httpd
  systemd: 
    state: started 
    name: httpd
  become: yes

- name: save httpd details
  copy: 
    content: >
       {
         "version": "{{ httpd_version.stdout }}",
         "installed": "{{ ansible_date_time.iso8601 }}"
       }
    dest: /etc/ansible/facts.d/httpd.fact
  become: yes