- hosts: localhost
  tasks:
  - debug:
      msg: "{{ hostvars[item].ansible_host }}"
    loop: "{{ groups.all }}"
    tags: destroy

  - name: smth
    gather_facts: no
    docker_container: 
      name: "{{ hostvars[item].ansible_host }}"
      state: absent
    loop: "{{ groups['all'] }}"
    become: yes
    tags:
      - destroy