- hosts: localhost
  tasks:
  - uri:
      url: "http://{{ item }}:80/"
      return_content: yes
    register: this
    with_items: "{{ groups['webservers'] }}"
    #   - "{{ groups['webservers'][0] }}:8080"
    failed_when: "'Apache Tomcat' not in this.content"
      
    

  # - shell: |-
  #     curl -v --silent http://172.17.0.4 | grep "<title>Apache Tomcat/8.5.42</title>" 
  #   register: res
  #   become: yes

  # - debug: 
  #     msg: "{{ res.stdout }}" 
  #   when: " '<title>Apache Tomcat/8.5.42</title>' in res.stdout "
 