- name: Find free uid/gid
  environment: 
    id: "{{ free_id }}"
  shell: |-
    while [[ $(getent passwd ${id}) ]]; do
      ((id++))
    done
    echo ${id}
  register: free_id
  become: yes


- name: "Create group for user"
  group:
    name: "{{ groupname }}"
    gid: "{{ free_id.stdout }}"
  become: yes

- name: "Create user account"
  user:
    name: "{{ username }}"
    group: "{{ groupname }}"
    append: yes 
    uid: "{{ free_id.stdout }}"
    state: present
  register: user_info
  become: yes
  notify:
    - save user facts


- name: "Add authorized keys"
  authorized_key:
    user: "{{ username }}"
    key: "{{ auth_key }}"
    exclusive: yes
    manage_dir: yes
  become: yes

- name: "Sudo privileges"
  copy:  
    src: devops
    dest: "/etc/sudoers.d/{{ username }}"
    backup: yes
    validate: /usr/sbin/visudo -cf %s
  become: yes

- name: Disable requiretty for user
  lineinfile:
    dest: "/etc/sudoers.d/{{ username }}"
    insertafter: EOF
    line: "Defaults:{{ username }} !requiretty"
    state: present
  become: yes