- hosts: localhost
  tasks:
  - name: Start Docker Container
    docker_container:
      name: "centos-{{ item }}"
      state: started
      image: sbeliakou/ansible-training:centos
      privileged: true
    with_sequence: count=5
    register: centos

  # - name: Compose In-Memory Inventory
  #   add_host:
  #     name: "{{ ansible_facts.docker_container.NetworkSettings.IPAddress }}"
  #     ansible_host: "{{ item.a }}"
  #     ansible_connection: docker
  #     group: "{{ item.b }}"
  #   with_items:
  #     - { a: "[{{ centos.results[0] }}]", b: loadbalancer }
  #     - { a: "[{{ centos.results[1] }}]", b: backends }
  #     - { a: "[{{ centos.results[2] }}]", b: backends }
  #     - { a: "[{{ centos.results[3] }}]", b: backends }
  #     - { a: "[{{ centos.results[4] }}]", b: backends }

  - name: Compose In-Memory Inventory
    add_host:
      name: "{{ container.NetworkSettings.IPAddress }}"
      ansible_host: "{{ container.Name }}"
      ansible_connection: docker
      groups:
        - loadbalancer
    loop: "[{{ centos.results[0] }}]"
    loop_control:
      label: "{{ container.Name }}"
    vars:
      container: "{{ item.ansible_facts.docker_container }}"

  - name: Compose In-Memory Inventory
    add_host:
      name: "{{ container.NetworkSettings.IPAddress }}"
      ansible_host: "{{ container.Name }}"
      ansible_connection: docker
      groups:
        - backends
    loop: "{{ centos.results[1:] }}"
    loop_control:
      label: "{{ container.Name }}"
    vars:
      container: "{{ item.ansible_facts.docker_container }}"

  - debug: var=groups

- hosts: all
  roles:
    - nginx_install

- hosts: localhost
  tasks:
  - name: Destroy
    gather_facts: no
    docker_container: 
      name: "{{ hostvars[item].ansible_host }}"
      state: absent
    loop: "{{ groups['backends'] + groups['loadbalancer'] }}"
    tags:
      - destroy

