---

- name: Installation prerequisites
  yum: 
    name: "{{ item }}" 
    state: present
  with_items:
    #- "java-{{ jdk_version }}-openjdk"
    - "java-{{ jdk_version }}-openjdk-devel"
  notify:
    - save java details
  become: yes

- name: Get info about java
  shell: |-
    java -version 2>&1 | awk '/version/{print $3}'
  register: java_version
  notify:
    - save java details
