- name: Mkdir for tomcat
  file:
    path: "{{ installation_home }}"
    state: directory
  become: yes

- name: Downloading Tomcat
  get_url: 
    url: "{{ tomcat_url }}"     
    dest: /tmp
  register: url_info
  become: yes

- name: Extracting archive
  unarchive:
    src: "{{ url_info.dest }}"
    dest: "{{ installation_home }}"
    remote_src: yes
  become: yes

- name: Movement provision scripts
  copy:
    src: files/setenv.sh
    dest: "{{ catalina_home }}/bin/setenv.sh"
    mode: '755'
  become: yes


- name: Movement provision scripts 
  template:
    src: tomcat.service.j2
    dest: "{{ services_home }}"
  become: yes

- name: Changing ownership of Tomcat installation
  file: 
    path: "{{ installation_home }}"
    owner: "{{ tomcat_user }}" 
    group: "{{ tomcat_group }}"
    state: directory 
    recurse: yes
  become: yes

- name: Changing mode for *.sh
  shell: "chmod 755 {{ catalina_home }}/bin/*.sh"
  become: yes
  notify:
    - systemd daemon reload
    - restart tomcat
    - save tomcat details
